### ISSUE TITLE
Compressed (zipped) Folders Error

### ISSUE THREAD

**Issue by walsu** [pipetcpt/DallphinAtoM#2]
안녕하세요, Github에 별로 익숙하진 않지만 한번 남겨봅니다. 

![image](https://user-images.githubusercontent.com/9631440/60391700-9c697280-9ac2-11e9-882e-ba61572864cb.png)

이 링크에 있는 파일 다운로드하고 압축파일 풀려고 하니 에러가 발생하네요. 확인 부탁 드립니다. 
http://pipet.or.kr/board/apps_view.asp?curPage=1&keyword=&idx=1050

**Comment by shanmdphd** [comment]
@walsu 선생님,
확인해 보았는데 저는 이상없이 압축이 풀렸습니다. 아마 다운로드가 완전히 이루어진게 아닌지요?

Github Releases에도 같은 파일을 압축 없이 올려놓았으니 이것으로 한번 시도해 보시겠어요?
https://github.com/pipetcpt/dallphin/releases/tag/v0.8.7

피드백 주셔서 감사드립니다. 소프트웨어 사용하시고 의견 주시면 적극 참고하겠습니다. ^^

**Comment by walsu** [comment]
링크로 가서 'install_dallphin_atom.ver.0.8.7.exe' 파일을 직접 다운로드 받아서 설치하는 것은 성공했습니다. 
pipet 홈페이지에 링크된 zip 파일은 여전히 해결이 되지 않네요. 
pipet 홈페이지 zip파일을 세번 받아봤는데 파일크기가 70.3/70.3/48.8 mb 입니다. 혹시나 해서 다른 랩탑에서 다운로드 받아봤는데 신기하게 파일크기가 37.1/25.3/25.3 mb 네요. 
인터넷이 중간에 끊기는것 같지는 않고 세번중에 두번은 파일크기가 같은것을 보면 뭔가 파일이 있는 서버와 관련된게 아닐까 싶은데 그쪽은 잘 모르겠습니다. 
두 랩탑 모두 윈도우 10입니다.

**Comment by shanmdphd** [comment]
해외(미국)에서 고용량 파일 (>100MB)를 다운로드 받을 때 저희 홈페이지 서버가 다소 불안정한게 아닐까 의심됩니다. 원인을 파악해 보겠습니다.

**Comment by shanmdphd** [comment]
@walsu 선생님, 에러를 보고해 주셔서 정말 감사드립니다. 

그런데 제가 여러 컴퓨터, 운영체제, 다양한 브라우저에서 다운로드를 시도했는데 그와 같은 에러를 재현하는데 실패하였습니다. 다운로드가 다 잘되고 있어서요.. 다운로드 받으실 시기에 서버가 일시적으로 문제가 있었던게 아닐까 의심하고 있습니다.

혹시 한번만 더 시도해 보아 주시고, 같은 현상 발생시 OS, 브라우저, WiFi 사용 유무 등을 정리해서 보고해 주실 수 있을런지요? 감사합니다.

**Comment by walsu** [comment]
> @walsu 선생님, 에러를 보고해 주셔서 정말 감사드립니다.
> 
> 그런데 제가 여러 컴퓨터, 운영체제, 다양한 브라우저에서 다운로드를 시도했는데 그와 같은 에러를 재현하는데 실패하였습니다. 다운로드가 다 잘되고 있어서요.. 다운로드 받으실 시기에 서버가 일시적으로 문제가 있었던게 아닐까 의심하고 있습니다.
> 
> 혹시 한번만 더 시도해 보아 주시고, 같은 현상 발생시 OS, 브라우저, WiFi 사용 유무 등을 정리해서 보고해 주실 수 있을런지요? 감사합니다.

**Comment by walsu** [comment]
Windows 10, chrome browser, wifi 사용중입니다. Firefox, IE 에서도 시도해 봤는데 같은 현상이고요. 최종 다운로드 받은 파일 사이즈가 브라우저마다 조금씩 다릅니다. 
학교내 네트워크를 사용하는거라 혹시 보안문제가 있을 수 있을까 했는데 지난번 올린건 집에서 테스트해보고 올린거라 그런 문제는 아닐것 같습니다. 랩탑도 개인랩탑으로도 테스트를 해봤으니 문제가 아니고요. 혹시 링크된 파일을 대용량 메일이나 클라우드 링크로 보내주실수 있나요? 한번 확인해 보겠습니다.

**Comment by walsu** [comment]
실수로 닫혀서 다시 엽니다.

**Comment by shanmdphd** [comment]
별다른 코멘트 없이 닫혀서 잘 해결 됐는줄 알았는데 여전히 문제가 남아있었군요.
구글 드라이브로 파일을 공유합니다. 
20190625123724_install_dallphin_atom(ver 0.8.7).zip - 176.077 MB

https://drive.google.com/file/d/1lTA7sfu_3HY11PiAHIa15FZLr8GZNefz/view?usp=sharing

**Comment by shanmdphd** [comment]
![image](https://user-images.githubusercontent.com/6946821/60563012-e8533a80-9d94-11e9-9af4-d2480e6c8550.png)

@walsu 선생님, 
VPN으로 미국이나 유럽에서 접속하는 것으로 해보니 말씀하신 상황을 재현할 수 있었습니다. 
저희 서버가 대용량 파일 전송에 최적화되지 않은 것으로 생각됩니다. 

저희 내부적으로 조사해서 해결하도록 하겠습니다. 
대단히 감사합니다.

**Comment by walsu** [comment]
링크해 주신 파일은 잘 됩니다. 저런 문제는 생각도 못했네요. 
소프트웨어에 대한 피드백은 써보고 나중에 올리겠습니다.

**Comment by shanmdphd** [comment]
네 0.8.8 버전이 어제 나왔으니 그것을 사용해 주세요 ^^ 감사합니다.
https://github.com/pipetcpt/dallphin/releases/tag/v0.8.8
