### ISSUE TITLE
1. Simulation Time 설정법에 대한 질문/ 2. Full PBPK에서 CL 오류

### ISSUE THREAD

**Issue by walsu** [pipetcpt/DallphinAtoM#4]
0.9.0 ver 설치해서 실행해 보았습니다. 깔끔하게 잘 만들어진것 같습니다.

Basic info 부터 Final Parameters 탭까지는 적당히 값 입력해서 넘어왔고요.
Concentration Prediction tab에서 'Run Simulation' 버튼을 눌렀는데 아무런 결과가 나오지 않습니다. 
Simulation Time 부분이 0.0으로 되어 있고 활성화가 되어 있지 않는데 이 부분 때문인것 같습니다.

![image](https://user-images.githubusercontent.com/9631440/86173509-15444580-baee-11ea-9a82-28ebb8df7f74.png)

참고로 Dosing Interval을 바꾸면 같은 값이 Simulation Time에 업데이트 되고 시뮬레이션이 잘 수행됨을 확인했습니다. 
Simulation Time = Number of Doses * Dosing Interval 로 설정되어 있는것 같습니다. 
![image](https://user-images.githubusercontent.com/9631440/86173794-871c8f00-baee-11ea-85d7-f09d5efb3214.png)

같은 원리가 Full PBPK 파트에도 적용되는것 같습니다. 추가로 Full PBPK 시뮬레이션 하면 plasma와 tissue concentration 모두 계속 올라가다 떨어지지 않고 유지되는데 제가 입력한 input 값 때문인지 잘 모르겠습니다. 
![image](https://user-images.githubusercontent.com/9631440/86174361-7ddff200-baef-11ea-9dae-c321b28240f8.png)
![image](https://user-images.githubusercontent.com/9631440/86174377-83d5d300-baef-11ea-96a1-0390d3f54a0a.png)

**Comment by shanmdphd** [comment]
@walsu 박사님, 안녕하세요? 일찍 글을 남겨주셨는데 제가 확인이 좀 늦었습니다. 버그 보고해 주셔서 감사드립니다.

- 첫번째 이슈는 단회투여의 경우 말씀하신 대로 simulation time이 설정되어 있습니다. 혼동되는 부분이 있어 다음 버전에서 개선이 이뤄질 예정입니다.
- 두번쨰 이슈는 result folder에 있는 csv 파일 등을 복사해서 여기 올려주시면 검토해보도록 하겠습니다. 아마 제거 관련 파라메터 값을 살펴보아야 할 것 같습니다.

> 영원히 몸속에서 빠져나가지 않는 물질..?

**Comment by sueinchoi** [comment]
@walsu 좋은 지적 감사합니다. 이 문제를 해결하기 위하여 원래는 Simulation time을 default는 자동 계산 값이지만 User가 원하면 바꿀 수 있도록 해놓은 걸로 알고있었는대 중간에 오류가 생긴것 같네요 ^^ 확인해 보고 다음 업데이트때에 올려드리도록 하겠습니다. 

두번째 이슈는 INPUT값일 가능성도 있지만 pbpk 모델로 들어가는 dallphin에서의 중간 계산 값이 적절히 들어가지 않았을 가능성도 있을 것 같아서 (특히 CL) parameter 값이 생성되는 csv파일을 주시면 input값을 확인해보고 코드에 오류가 있으면 수정하도록 하겠습니다 ^^

좋은 의견 감사드립니다~ 내부적으로 충분한 테스트가 이뤄지지 않은 부분이 있어 이런 부분을 확인하지 못한점 사과 드리면 부족한 만큼 선생님의 의견 하나하나가 도움이 많이 될 것 같아 앞으로도 잘 부탁드립니다...ㅎㅎ
제가 확인해보고 빠른 시일 내에 다음 업데이트 시 반영하여 배포하도록 하겠습니다.

**Comment by walsu** [comment]
inputParameter 파일을 보니 full PBPK  테스트 과정에서 Elimination 부분을 제대로 안넣었던것 같습니다.  CLrenal, CLmet 모두 0으로 되어 있네요. 각 탭에 값을 어떻게 설정했는지는 복원을 못하겠고 아래는 당시 적용됐던 full PBPK 의 input parameter 입니다.  두번째 이슈도 일단 해결된것 같습니다만 어떤 과정에서 그렇게 됐는지는 다시 사용해 보면서 찾아보겠습니다. 

CLrenal=0.0;
 CLmet=0.0;
 fu_hum=0.1;
 CbCp=1.0;
 Ka_hum=0.21;
 FAFG=0.18135813844646279;
 Kpad=2.3316860211660617;
 Kpbo=5.761237882994149;
 Kpbr=5.421723935920046;
 Kpgu=4.3342114560509835;
 Kphe=1.5588393477988551;
 Kpki=2.231662374816881;
 Kpli=3.479934320821335;
 Kplu=0.749827288363549;
 Kpsk=2.6570790768009833;
 Kpsp=2.2802331625844716;
 Kpre=2.6570790768009833;
 dtype=PO;
 rate=1;
 addl=1;
 ii=100;
 path=c:\DAllPhin-AtoM\results\fullpbpk\2020-06-30-16-32-38\;
 dose=1;
 BW=70;

**Comment by shanmdphd** [comment]
@sueinchoi 선생님, 답변 감사합니다. 🌷 
@dlaqudgml2 선생님,  v0.9.1 에 반영하면 좋을거 같아요. 🖱️ 

---

두번째 이슈 관련,

```r
CLrenal = as.numeric(input$CLrenal), ## Renal clearance selected **** SELECTED
CLmet = as.numeric(input$CLmet), ## Final selected intrinsic clearance (L/hr) **** SELECTED !! Call me
```

아마 `Final Parameter` 탭에서 선택한 값이 PBPKcode.R로 전달되는 구조로 보이는데, 

1. 라디오버튼의 클릭이 안되었거나, (그랬다면 Full PBPK 뿐만 아니라 Conc. Prediction 도 안그려졌을거 같아요.) 
2. 선택된 값이 Full PBPK 부분으로 전달이 안된게 아닌가 싶네요. (그랬다면 NA값이 넘어갔을텐데, 0이 입력된거도 의아하긴 합니다.)

@walsu 선생님,
참고로 말씀드리자면 `C:\DAllPhin-AtoM\R\code\PBPKcode2.R` 에서 full PBPK 코드가 위치해 있습니다.
*원하신다면* 선생님께서 값을 임의로 바꾸시면서 테스트해 보실 수 있을거 같습니다 😄

**Comment by pipetpro** [comment]
Allometry만 쓰는 경우 Full PBPK에서 CL이 잘 안나올 수 있습니다.
에러메세지를 표시하던지, 역산하여 계산하는 등의 방법을 세워 CL 값을 계산하도록 개선하겠습니다.
